engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: true
exclude_paths:
- node_modules/**/*
- build/**/*
- extension/data/libs/**/*
- gulpfile.js
ratings:
   paths:
   - extension/**/*